# Generated by Django 3.2.18 on 2023-03-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.IntegerField()),
                ('orderDate', models.DateTimeField()),
                ('shippedDate', models.DateTimeField(blank=True)),
                ('totalValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderStatus', models.CharField(choices=[('PENDING', 'PENDING'), ('SHIPPING', 'SHIPPING'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
