# Generated by Django 3.2.18 on 2023-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalValue',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
