# Generated by Django 3.2.18 on 2023-03-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_totalvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
